version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_API_URL=/api
      - REACT_APP_GOOGLE_MAPS_API_KEY=AIzaSyBH6USjQTfrtlroPqyNWxu7i5mcvtQRAOk
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped

networks:
  charging-network:
    driver: bridge
volumes:
  nginx-logs:
